
services:
  chirpstack:
    # image: chirpstack/chirpstack:4
    build: 
      context: configuration/chirpstack
    command: -c /etc/chirpstack # import-legacy-lorawan-devices-repository -d /tmp/lorawan-devices
    restart: unless-stopped
    # volumes:
    #   - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto  # Use service name
      - REDIS_HOST=redis            # Use service name
      - POSTGRESQL_HOST=postgres    # Use service name
    ports:
      - "47834:47834"

  chirpstack-gateway-bridge:
    # image: chirpstack/chirpstack-gateway-bridge:4
    build: 
      context: configuration/chirpstack-gateway-bridge
    restart: unless-stopped
    ports:
      - "47837:47837/udp"
    # volumes:
    #   - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__SERVER=mosquitto:47833  # Use service name
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
    depends_on:
      - mosquitto

  chirpstack-gateway-bridge-basicstation:
    # image: chirpstack/chirpstack-gateway-bridge:4
    build: 
      context: configuration/chirpstack-gateway-bridge
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
    ports:
      - "47830:47830" # CUPS / LNS
    # volumes:
    #   - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__SERVER=mosquitto:47833  # Use service name
    depends_on:
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:47834 --bind 0.0.0.0:47835 --insecure  # Use service name
    ports:
      - "47835:47835"
    depends_on:
      - chirpstack

  postgres:
    # image: postgres:14-alpine
    build: 
      context: configuration/postgresql
    restart: unless-stopped
    volumes:
      # - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - redisdata:/data

  mosquitto:
    # image: eclipse-mosquitto:2
    build: 
      context: configuration/mosquitto
    restart: unless-stopped
    ports:
      - "47833:47833"
    # volumes:
    #   - ./configuration/mosquitto/config/:/mosquitto/config/

  ironflock_publisher:
    # image: chirpstack/chirpstack:4
    build: 
      context: ironflock_publish
    restart: unless-stopped
    # volumes:
    #   - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      - chirpstack
      - mosquitto

volumes:
  postgresqldata:
  redisdata: