FROM chirpstack/chirpstack:4

COPY . /etc/chirpstack/

# USER root

# RUN apk add --no-cache git && \
# 	git clone https://github.com/brocaar/lorawan-devices /tmp/lorawan-devices && \
# 	chirpstack -c /etc/chirpstack import-legacy-lorawan-devices-repository -d /tmp/lorawan-devices